site_name: HyDLPy
site_description: A hybrid hydrological modeling framework powered by deep learning
site_url: https://chooron.github.io/hydlpy/
repo_name: chooron/hydlpy
repo_url: https://github.com/chooron/hydlpy

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - Estimators: estimators.md
  - Models: models.md
  - Training: training.md
  - Model Building Guide: build_hydrological_model.md

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chooron/hydlpy
